import { NextRequest, NextResponse } from 'next/server';
import Stripe from 'stripe';

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: '2023-10-16',
  });

  export async function POST(req: NextRequest) {
    try {
        const { plan } = await req.json();
            const origin = req.headers.get('origin') || 'http://localhost:3000';

                let sessionConfig: Stripe.Checkout.SessionCreateParams;

                    if (plan === 'payment_plan') {
                          // 3 payments of $867/month
                                sessionConfig = {
                                        mode: 'subscription',
                                                line_items: [
                                                          {
                                                                      price_data: {
                                                                                    currency: 'usd',
                                                                                                  product_data: {
                                                                                                                  name: 'HighIQ Accelerator - Payment Plan',
                                                                                                                                  description: '90-Day Intensive Program (3 monthly payments)',
                                                                                                                                                },
                                                                                                                                                              unit_amount: 86700, // $867.00 in cents
                                                                                                                                                                            recurring: {
                                                                                                                                                                                            interval: 'month',
                                                                                                                                                                                                            interval_count: 1,
                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                  quantity: 1,
                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                            subscription_data: {
                                                                                                                                                                                                                                                                                      metadata: {
                                                                                                                                                                                                                                                                                                  max_payments: '3',
                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                            success_url: `${origin}/success?session_id={CHECKOUT_SESSION_ID}`,
                                                                                                                                                                                                                                                                                                                                    cancel_url: `${origin}/`,
                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                              } else {
                                                                                                                                                                                                                                                                                                                                                    // Full payment of $2,500
                                                                                                                                                                                                                                                                                                                                                          sessionConfig = {
                                                                                                                                                                                                                                                                                                                                                                  mode: 'payment',
                                                                                                                                                                                                                                                                                                                                                                          line_items: [
                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                price_data: {
                                                                                                                                                                                                                                                                                                                                                                                                              currency: 'usd',
                                                                                                                                                                                                                                                                                                                                                                                                                            product_data: {
                                                                                                                                                                                                                                                                                                                                                                                                                                            name: 'HighIQ Accelerator',
                                                                                                                                                                                                                                                                                                                                                                                                                                                            description: '90-Day Intensive: AI CRM + Ads + Coaching + Training',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        unit_amount: 250000, // $2,500.00 in cents
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                quantity: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          success_url: `${origin}/success?session_id={CHECKOUT_SESSION_ID}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  cancel_url: `${origin}/`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const session = await stripe.checkout.sessions.create(sessionConfig);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return NextResponse.json({ url: session.url });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (error: any) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.error('Stripe checkout error:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return NextResponse.json(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    { error: error.message || 'Failed to create checkout session' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          { status: 500 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
